- name: File level variables
  hosts: local
  connection: local

  # vars_files:
  #   - course.yaml

  tasks:
    - name: Print file level variables
      vars:
        course: "ansible"
      ansible.builtin.debug:
        msg: "Course is: {{ course }}, Trainer is: {{ Trainer }}"