- name: file level variables
  hosts: local
  connection: local

  vars_files:
   - course.yaml
  tasks:
   - name: print file level variables
     vars:
      course: "ansible"
      ansible.builtin.debug:
       msg: "course is: {{course}}, Trainer is: {{Trainer}}" 