- name: print username and password
  hosts: local
  connection: local
  # print the prompts
  vars_prompt:
  - name: username
    prompt: please enter the your username
    private: false

  - name: password
    prompt: please enter the password
    private: true

  tasks:
  - name: print username and password
    ansible.builtin.debug:
     msg: "username is: {{username}}, password is: {{password}}"